pull_request_rules:
  # approve
  - name: automatic approval
    conditions:
      - author=dsm23
      - check-success=build
      - check-success=format
      - check-success=lint
    actions:
      review:
        type: APPROVE
        message: Automatically approving dsm23
  - name: automatic approval for Renovate pull requests
    conditions:
      - author=renovate[bot]
      - check-success=build
      - check-success=format
      - check-success=lint
    actions:
      review:
        type: APPROVE
        message: Automatically approving renovate
  # merge
  - name: Automatically merge when GitHub Actions jobs succeed
    conditions:
      - check-success=build
      - check-success=format
      - check-success=lint
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: merge
